'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
export function AgreementManager(){
 const [rows,setRows]=useState<any[]>([]); const [form,setForm]=useState({agreement_type:'IDEA_EVALUATION',version:'',title:'Idea Evaluation & Collaboration Agreement',body:'',active:true}); const [msg,setMsg]=useState('');
 async function load(){try{setRows(await api<any[]>('/admin/agreements'))}catch(e:any){setMsg(e.message)}} useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setMsg('');try{await api('/admin/agreements',{method:'POST',body:JSON.stringify(form)});setForm({...form,version:'',body:''});await load();setMsg('New immutable agreement version created.')}catch(e:any){setMsg(e.message)}}
 async function setActive(id:number,active:boolean){try{await api(`/admin/agreements/${id}`,{method:'PATCH',body:JSON.stringify({active})});await load()}catch(e:any){setMsg(e.message)}}
 return <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><form onSubmit={create} className="card space-y-4 p-6"><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">NEW VERSION</div><h2 className="text-2xl font-semibold">Publish a new agreement</h2><p className="text-sm leading-7 text-[var(--muted)]">Agreement versions are immutable after creation. Create v1.1 rather than editing an accepted v1.0.</p><input className="input" placeholder="Version, e.g. 1.1" required value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/><input className="input" placeholder="Title" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="input min-h-72 font-mono text-xs" placeholder="Agreement text" required value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Make this the active version</label><button className="btn btn-dark">Create version</button>{msg&&<div className="text-sm">{msg}</div>}</form><div className="space-y-4">{rows.map(r=><article key={r.id} className="card p-5"><div className="flex items-center justify-between gap-3"><div><div className="mono text-[10px] uppercase tracking-[.16em] text-[var(--muted)]">{r.agreement_type}</div><h3 className="mt-1 font-semibold">{r.title} · v{r.version}</h3></div><span className="status">{r.active?'ACTIVE':'INACTIVE'}</span></div><div className="mt-3 mono break-all text-[10px] text-[var(--muted)]">SHA-256 {r.sha256}</div><p className="mt-4 max-h-28 overflow-auto whitespace-pre-wrap text-sm leading-6 text-[var(--muted)]">{r.body}</p><button className="btn mt-4" onClick={()=>setActive(r.id,!r.active)}>{r.active?'Deactivate':'Make active'}</button></article>)}</div></div>
}
