'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api';

export function ProjectTechnologyEditor({projectId}:{projectId:number}){
 const [items,setItems]=useState<string[]>([]);const [draft,setDraft]=useState('');const [msg,setMsg]=useState('');
 useEffect(()=>{api<string[]>(`/public/projects/${projectId}/technologies`).then(setItems).catch(()=>{})},[projectId]);
 async function save(){const next=draft.split(',').map(x=>x.trim()).filter(Boolean);const merged=[...items,...next].filter((v,i,a)=>a.indexOf(v)===i).slice(0,30);try{await api(`/admin/projects/${projectId}/technologies`,{method:'PUT',body:JSON.stringify({technologies:merged})});setItems(merged);setDraft('');setMsg('Technologies saved.')}catch(e:any){setMsg(e.message)}}
 return <div className="mt-6 rounded-2xl border border-[var(--line)] bg-[var(--bg)] p-5"><div className="field-label">Project technology stack</div><div className="mt-3 flex flex-wrap gap-2">{items.length?items.map(x=><span className="status" key={x}>{x}</span>):<span className="text-sm text-[var(--muted)]">No technologies linked yet.</span>}</div><div className="mt-4 flex gap-2"><input className="input" placeholder="Add comma-separated technologies" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="btn btn-dark" type="button" onClick={save}>Save</button></div>{msg&&<div className="mt-3 text-xs text-[var(--muted)]">{msg}</div>}</div>
}

export function ResearchReferencesEditor({researchId}:{researchId:number}){
 const [items,setItems]=useState<any[]>([]);const [draft,setDraft]=useState({title:'',authors:'',venue:'',year:'',doi:'',url:'',citation_text:''});const [msg,setMsg]=useState('');
 useEffect(()=>{api<any[]>(`/admin/research/${researchId}/references`).then(setItems).catch(e=>setMsg(e.message))},[researchId]);
 function add(){if(!draft.title.trim()){setMsg('Reference title is required.');return}setItems([...items,{...draft,year:draft.year?Number(draft.year):null}]);setDraft({title:'',authors:'',venue:'',year:'',doi:'',url:'',citation_text:''});setMsg('Reference staged. Save references to persist it.')} 
 async function save(){try{const cleaned=items.map(x=>({title:x.title,authors:x.authors,venue:x.venue,year:x.year||null,doi:x.doi,url:x.url,citation_text:x.citation_text}));await api(`/admin/research/${researchId}/references`,{method:'PUT',body:JSON.stringify({references:cleaned})});setMsg('References saved.')}catch(e:any){setMsg(e.message)}}
 return <div className="mt-6 rounded-2xl border border-[var(--line)] bg-[var(--bg)] p-5"><div className="field-label">Structured research references</div><div className="mt-4 space-y-2">{items.map((x,i)=><div className="rounded-xl border border-[var(--line)] bg-white p-3 text-sm" key={i}><div className="flex items-start justify-between gap-3"><div><div className="font-medium">{x.title}</div><div className="text-xs text-[var(--muted)]">{x.authors}{x.venue?` · ${x.venue}`:''}{x.year?` · ${x.year}`:''}</div></div><button type="button" className="text-xs underline" onClick={()=>setItems(items.filter((_,n)=>n!==i))}>Remove</button></div></div>)}{!items.length&&<div className="text-sm text-[var(--muted)]">No structured references yet.</div>}</div><div className="mt-5 grid gap-3 md:grid-cols-2"><input className="input" placeholder="Reference title" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><input className="input" placeholder="Authors" value={draft.authors} onChange={e=>setDraft({...draft,authors:e.target.value})}/><input className="input" placeholder="Venue" value={draft.venue} onChange={e=>setDraft({...draft,venue:e.target.value})}/><input className="input" placeholder="Year" type="number" value={draft.year} onChange={e=>setDraft({...draft,year:e.target.value})}/><input className="input" placeholder="DOI" value={draft.doi} onChange={e=>setDraft({...draft,doi:e.target.value})}/><input className="input" placeholder="URL" type="url" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/><textarea className="input md:col-span-2" placeholder="Citation text (optional)" value={draft.citation_text} onChange={e=>setDraft({...draft,citation_text:e.target.value})}/></div><div className="mt-4 flex gap-2"><button type="button" className="btn" onClick={add}>Add reference</button><button type="button" className="btn btn-dark" onClick={save}>Save references</button></div>{msg&&<div className="mt-3 text-xs text-[var(--muted)]">{msg}</div>}</div>
}
