'use client';
import {useEffect,useState} from 'react';
import {api,API_BASE} from '../lib/api';
function safeParse(v:string){try{return JSON.parse(v)}catch{return []}}
export function RequestInbox(){
  const [rows,setRows]=useState<any[]>([]); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(''); const [links,setLinks]=useState<Record<string,any>>({}); const [expiry,setExpiry]=useState<Record<string,number>>({});
  async function load(){try{setRows(await api<any[]>('/admin/requests'))}catch(e:any){setMsg(e.message)}}
  useEffect(()=>{load()},[]);
  async function act(row:any,status:string){setBusy(row.request_id);setMsg('');try{await api(`/admin/requests/${row.request_id}`,{method:'PATCH',body:JSON.stringify({status,owner_notes:row.owner_notes||undefined})});await load();setMsg(`${row.request_id} is now ${status}.`)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
  async function issueLink(row:any){
    setBusy(row.request_id);setMsg('');
    try{const result=await api<any>(`/admin/requests/${row.request_id}/access-link`,{method:'POST',body:JSON.stringify({expires_days:Math.max(1,Math.min(3650,Number(expiry[row.request_id]||30)))})});setLinks({...links,[row.request_id]:result});setMsg(`Restricted access link issued for ${row.request_id}. Treat it like a password and send it only to the approved requester.`)}catch(e:any){setMsg(e.message)}finally{setBusy('')}
  }
  async function revokeLink(row:any){setBusy(row.request_id);setMsg('');try{await api(`/admin/requests/${row.request_id}/access-link`,{method:'DELETE'});setLinks({...links,[row.request_id]:null});await load();setMsg(`Restricted access link revoked for ${row.request_id}.`)}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
  async function copy(text:string){try{await navigator.clipboard.writeText(text);setMsg('Access link copied to clipboard.')}catch{setMsg('Copy failed. Select the link manually instead.')}}
  return <div className="space-y-4">
    {!rows.length&&<div className="card p-6 text-sm text-[var(--muted)]">No collaboration requests yet.</div>}
    {rows.map(row=><article key={row.request_id} className="card p-6">
      <div className="flex flex-col justify-between gap-4 md:flex-row">
        <div><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">{row.request_id} · {row.status}</div><h3 className="mt-2 text-xl font-semibold">{row.name}</h3><p className="mt-1 text-sm text-[var(--muted)]">{row.email}{row.organization?` · ${row.organization}`:''}{row.role?` · ${row.role}`:''}{row.country?` · ${row.country}`:''}</p></div>
        <div className="text-xs text-[var(--muted)]">Agreement {row.agreement_type} v{row.agreement_version}<br/>{new Date(row.accepted_at||row.created_at).toLocaleString()}</div>
      </div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">
        <div><div className="mb-3 flex flex-wrap gap-2"><span className="status">{row.request_kind==='INVESTOR_OUTREACH'?'Investor Outreach':row.request_kind==='FUNDING_REQUEST'?'Funding Request':'Collaboration'}</span>{row.funding_amount&&<span className="status">{row.funding_currency} {Number(row.funding_amount).toLocaleString()}</span>}</div><div className="field-label">Requested purpose</div><p className="text-sm leading-7 text-[var(--muted)]">{row.purpose}</p><div className="field-label mt-4">Requested rights</div><div className="flex flex-wrap gap-2">{safeParse(row.requested_rights).map((r:string)=><span key={r} className="status">{r}</span>)}</div></div>
        <div><div className="field-label">Requester profile</div><div className="space-y-1 text-sm">{row.professional_profile_url&&<a rel="noreferrer" className="underline" href={row.professional_profile_url} target="_blank">Professional profile →</a>}{row.website_url&&<a rel="noreferrer" className="block underline" href={row.website_url} target="_blank">Website →</a>}<div className="text-[var(--muted)]">Signature: {row.signature_name}</div><div className="text-[var(--muted)]">Accepted: {new Date(row.accepted_at).toLocaleString()}</div></div><div className="field-label mt-4">Accepted agreement hash</div><div className="mono break-all text-[10px] text-[var(--muted)]">{row.agreement_sha256}</div><div className="field-label mt-3">Network integrity hash</div><div className="mono break-all text-[10px] text-[var(--muted)]">{row.acceptance_ip_hash||'Not recorded'}</div></div>
      </div>
      <div className="mt-5 rounded-xl border border-[var(--line)] bg-[var(--bg)] p-4">{row.investment_interest&&<><div className="field-label">Investment interest</div><p className="text-sm leading-7 text-[var(--muted)]">{row.investment_interest}</p></>}{row.funding_amount&&<><div className="field-label mt-4">Funding request</div><p className="text-sm leading-7 text-[var(--muted)]">{row.funding_currency} {Number(row.funding_amount).toLocaleString()} · {row.funding_stage||'Stage not specified'} · {row.funding_instrument||'Instrument not specified'}</p>{row.funding_use&&<p className="mt-2 text-sm leading-7 text-[var(--muted)]">Use: {row.funding_use}</p>}{row.pitch_deck_url&&<a className="mt-2 inline-block underline text-sm" href={row.pitch_deck_url} target="_blank" rel="noreferrer">Pitch deck →</a>}</>}</div><details className="mt-5 rounded-xl border border-[var(--line)] bg-[var(--bg)] p-4">
        <summary className="cursor-pointer font-medium">View exact accepted agreement text</summary>
        <div className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[var(--muted)]">{row.agreement_body_snapshot||'Agreement snapshot not stored in this older record.'}</div>
      </details>
      <details className="mt-3 rounded-xl border border-[var(--line)] bg-[var(--bg)] p-4"><summary className="cursor-pointer font-medium">View site-terms evidence</summary><div className="mt-3 text-xs text-[var(--muted)]">Version {row.site_terms_version||'—'} · SHA-256 {row.site_terms_sha256||'—'}</div><div className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap text-sm leading-7 text-[var(--muted)]">{row.site_terms_body_snapshot||'No site-terms snapshot on this older record.'}</div></details><div className="mt-3 rounded-xl bg-[var(--bg)] p-4 text-sm leading-7">{row.message||'No additional message.'}</div><label className="mt-4 block"><span className="field-label">Owner notes</span><textarea className="input min-h-24" value={row.owner_notes||''} onChange={e=>setRows(rows.map(x=>x.request_id===row.request_id?{...x,owner_notes:e.target.value}:x))}/></label>
      <div className="mt-5 flex flex-wrap gap-2"><button className="btn btn-dark" disabled={!!busy||row.status==='APPROVED'} onClick={()=>act(row,'APPROVED')}>{busy===row.request_id?'Saving…':'Approve & grant requested rights'}</button><button className="btn" disabled={!!busy||row.status==='REJECTED'} onClick={()=>act(row,'REJECTED')}>Reject / revoke</button><button className="btn" disabled={!!busy||row.status==='NEEDS_INFO'} onClick={()=>act(row,'NEEDS_INFO')}>Request more info</button></div>
      {row.status==='APPROVED'&&row.idea_id&&<div className="mt-5 rounded-2xl border border-dashed border-[var(--line)] p-5"><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">RESTRICTED ACCESS</div><h4 className="mt-2 font-semibold">Controlled detail link</h4><p className="mt-2 text-sm leading-6 text-[var(--muted)]">This bearer URL exposes the approved idea's restricted detail. It is separate from the public page and can be revoked.</p><div className="mt-4 flex flex-wrap gap-2"><label className="flex items-center gap-2 text-sm"><span className="field-label !mb-0">Days</span><input className="input w-24" type="number" min="1" max="3650" value={expiry[row.request_id]||30} onChange={e=>setExpiry({...expiry,[row.request_id]:Number(e.target.value)})}/></label><button className="btn btn-dark" disabled={!!busy} onClick={()=>issueLink(row)}>Issue restricted link</button><button className="btn" disabled={!!busy} onClick={()=>revokeLink(row)}>Revoke link</button></div>{links[row.request_id]&&<div className="mt-4 rounded-xl bg-[var(--bg)] p-4"><div className="field-label">Restricted bearer URL</div><div className="break-all text-sm">{API_BASE.replace('/api/v1','')}{links[row.request_id].access_path}</div><div className="mt-3 flex flex-wrap gap-2"><button className="btn" onClick={()=>copy(`${API_BASE.replace('/api/v1','')}${links[row.request_id].access_path}`)}>Copy link</button><span className="status">Expires {new Date(links[row.request_id].expires_at).toLocaleDateString()}</span></div><p className="mt-3 text-xs leading-5 text-[var(--muted)]">The secret token is stored only as a hash on the server. The URL above is shown in this admin session so you can send it to the approved requester.</p></div>}</div>}
    </article>)}
    {msg&&<div className="card p-4 text-sm">{msg}</div>}
  </div>
}
