'use client';
import {Suspense,useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Section} from '../../components/Section';
import {Turnstile} from '../../components/Turnstile';
import {api} from '../../lib/api';

const RIGHTS=['Concept','Technical documentation','Prototype','Source code','Dataset','Research','Collaboration','Commercial development'];
const REQUEST_TYPES=[
  ['COLLABORATION','Collaboration / Build Together'],
  ['INVESTOR_OUTREACH','Investor / Investment Discussion'],
  ['FUNDING_REQUEST','Funding Request / Seeking Support'],
] as const;
const AGREEMENT_BY_KIND:Record<string,[string,string]>= {
  COLLABORATION:['COLLABORATION','General Collaboration Agreement'],
  INVESTOR_OUTREACH:['INVESTOR_DISCUSSION','Investor Discussion Agreement'],
  FUNDING_REQUEST:['FUNDING_REQUEST','Funding Request Agreement'],
};

function CollaborateForm(){
 const sp=useSearchParams();
 const idea=sp.get('idea')||'';
 const [kind,setKind]=useState(idea?'COLLABORATION':'COLLABORATION');
 const [ag,setAg]=useState<any>(); const [terms,setTerms]=useState<any>();
 const [f,setF]=useState({name:'',email:'',organization:'',role:'',country:'',professional_profile_url:'',website_url:'',purpose:'',rights:['Concept'],message:'',signature_name:'',honeypot:'',investment_interest:'',funding_amount:'',funding_currency:'INR',funding_stage:'',funding_instrument:'',funding_use:'',pitch_deck_url:''});
 const [accepted,setAccepted]=useState(false); const [termsAccepted,setTermsAccepted]=useState(false); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false); const [turnstileToken,setTurnstileToken]=useState('');
 const selectedAgreement=AGREEMENT_BY_KIND[kind];
 useEffect(()=>{Promise.all([api<any>(`/public/agreements/${selectedAgreement[0]}`),api<any>('/public/agreements/SITE_TERMS')]).then(([a,t])=>{setAg(a);setTerms(t)}).catch(e=>setMsg(e.message));setAccepted(false)},[kind]);
 function toggle(r:string){setF(v=>({...v,rights:v.rights.includes(r)?v.rights.filter(x=>x!==r):[...v.rights,r]}))}
 async function submit(e:React.FormEvent){e.preventDefault(); if(!ag||!terms||!accepted||!termsAccepted){setMsg('Please read and accept the current agreements.');return} if(f.signature_name.trim().toLowerCase()!==f.name.trim().toLowerCase()){setMsg('Typed signature must exactly match the full name.');return} if(kind==='FUNDING_REQUEST' && !f.funding_amount){setMsg('Funding amount is required for a Funding Request.');return}
  setBusy(true); try{const r=await api<any>('/collaboration-requests',{method:'POST',body:JSON.stringify({...f,request_kind:kind,requested_rights:f.rights,agreement_type:ag.agreement_type,agreement_version:ag.version,agreement_sha256:ag.sha256,site_terms_version:terms.version,site_terms_sha256:terms.sha256,privacy_acknowledged:true,idea_public_id:idea||null,turnstile_token:turnstileToken,funding_amount:f.funding_amount?Number(f.funding_amount):null,pitch_deck_url:f.pitch_deck_url||null})});setMsg(`Request ${r.request_id} submitted. The owner can now review it.`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <main className="fade"><Section eyebrow="COLLABORATE" title={idea?`Request to work on ${idea}`:'Start a conversation'}><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]">
 <div><div className="card p-6"><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">COLLABORATION HUB</div><h2 className="mt-3 text-2xl font-semibold">Choose what you want to discuss.</h2><p className="mt-3 leading-7 text-[var(--muted)]">Investor outreach and funding requests are recorded separately from ordinary collaboration so the owner can understand the purpose, supporting information and requested next step.</p></div>
 <div className="mt-5 card p-6"><div className="field-label">Request type</div><div className="grid gap-3">{REQUEST_TYPES.map(([v,l])=><button key={v} type="button" onClick={()=>{setKind(v);setF(x=>({...x,rights:v==='INVESTOR_OUTREACH'?['Collaboration']:x.rights}))}} className={`rounded-xl border p-4 text-left ${kind===v?'border-[var(--fg)] bg-[var(--fg)] text-white':'border-[var(--line)] bg-white'}`}><div className="font-semibold">{l}</div><div className={`mt-1 text-xs leading-5 ${kind===v?'text-white/75':'text-[var(--muted)]'}`}>{v==='INVESTOR_OUTREACH'?'Discuss investment, strategic backing or investor collaboration.':v==='FUNDING_REQUEST'?'Request financial support for a project, research, product or concept.':'Build, research, mentor or otherwise collaborate.'}</div></button>)}</div></div>
 {ag&&<div className="mt-5 card p-6"><div className="flex items-center justify-between gap-4"><h3 className="font-semibold">{ag.title}</h3><span className="status">v{ag.version}</span></div><p className="mt-3 text-xs leading-6 text-[var(--muted)]">SHA-256 integrity record: {ag.sha256}</p><pre className="mt-4 max-h-72 overflow-auto whitespace-pre-wrap border-y border-[var(--line)] py-4 text-sm leading-7 text-[var(--muted)]">{ag.body}</pre><label className="mt-5 flex gap-3 text-sm leading-6"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I have read and accept this agreement version for this specific request. Acceptance does not itself grant permission.</span></label></div>}
 <div className="mt-5 card p-6"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">Website Terms · v{terms?.version||'—'}</h3><span className="status">SHA-256 {terms?.sha256?.slice(0,16)||'—'}…</span></div><label className="mt-4 flex gap-3 text-sm leading-6"><input type="checkbox" checked={termsAccepted} onChange={e=>setTermsAccepted(e.target.checked)}/><span>I have read and accept the current Website Terms of Use and Privacy Policy for this request.</span></label></div>
 <div className="mt-5 rounded-2xl border border-dashed border-[var(--line)] bg-white p-6 text-sm leading-7 text-[var(--muted)]">For potentially patentable, investment-sensitive or commercially confidential material, consider appropriate professional IP/legal advice before disclosure.</div></div>
 <form onSubmit={submit} className="card space-y-4 p-7"><input className="sr-only" tabIndex={-1} autoComplete="off" value={f.honeypot} onChange={e=>setF({...f,honeypot:e.target.value})} aria-hidden="true"/><input className="input" placeholder="Full name / contact person" required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input className="input" type="email" placeholder="Email" required value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><div className="grid gap-4 md:grid-cols-2"><input className="input" placeholder="Organization / fund / company" value={f.organization} onChange={e=>setF({...f,organization:e.target.value})}/><input className="input" placeholder="Role / title" value={f.role} onChange={e=>setF({...f,role:e.target.value})}/></div><div className="grid gap-4 md:grid-cols-2"><input className="input" placeholder="Professional profile URL" type="url" value={f.professional_profile_url} onChange={e=>setF({...f,professional_profile_url:e.target.value})}/><input className="input" placeholder="Website" type="url" value={f.website_url} onChange={e=>setF({...f,website_url:e.target.value})}/></div><input className="input" placeholder="Country" value={f.country} onChange={e=>setF({...f,country:e.target.value})}/>
 {kind==='INVESTOR_OUTREACH'&&<div><div className="field-label">Investment interest</div><textarea className="input min-h-24" placeholder="What attracts you to the work, and what kind of investment or strategic support are you interested in?" value={f.investment_interest} onChange={e=>setF({...f,investment_interest:e.target.value})}/></div>}
 {kind==='FUNDING_REQUEST'&&<div className="rounded-2xl border border-[var(--line)] bg-[var(--bg)] p-5 space-y-4"><div className="field-label">Funding request</div><div className="grid gap-4 md:grid-cols-[1fr_110px]"><input className="input" type="number" min="1" step="0.01" placeholder="Amount" required value={f.funding_amount} onChange={e=>setF({...f,funding_amount:e.target.value})}/><input className="input uppercase" maxLength={3} value={f.funding_currency} onChange={e=>setF({...f,funding_currency:e.target.value.toUpperCase().slice(0,3)})}/></div><div className="grid gap-4 md:grid-cols-2"><input className="input" placeholder="Stage (idea, prototype, growth…)" value={f.funding_stage} onChange={e=>setF({...f,funding_stage:e.target.value})}/><input className="input" placeholder="Instrument (equity, grant, loan…)" value={f.funding_instrument} onChange={e=>setF({...f,funding_instrument:e.target.value})}/></div><textarea className="input min-h-24" placeholder="How would the funding be used?" value={f.funding_use} onChange={e=>setF({...f,funding_use:e.target.value})}/><input className="input" type="url" placeholder="Pitch deck URL (optional)" value={f.pitch_deck_url} onChange={e=>setF({...f,pitch_deck_url:e.target.value})}/></div>}
 <textarea className="input min-h-32" placeholder={kind==='INVESTOR_OUTREACH'?'What would you like to discuss?':kind==='FUNDING_REQUEST'?'Describe the project, funding need and expected use of funds.':'What would you like to build, research or discuss?'} required value={f.purpose} onChange={e=>setF({...f,purpose:e.target.value})}/>{kind==='COLLABORATION'&&<div><div className="mb-2 text-sm font-medium">Requested rights / access</div><div className="grid gap-2 sm:grid-cols-2">{RIGHTS.map(r=><label key={r} className="flex gap-2 text-sm text-[var(--muted)]"><input type="checkbox" checked={f.rights.includes(r)} onChange={()=>toggle(r)}/>{r}</label>)}</div></div>}
 {kind!=='COLLABORATION'&&<p className="rounded-xl bg-[var(--bg)] p-4 text-sm leading-6 text-[var(--muted)]">Investor and funding requests do not automatically receive rights to private ideas, source code or confidential documents. Any such access must be separately approved by the owner.</p>}
 <textarea className="input min-h-24" placeholder="Additional message" value={f.message} onChange={e=>setF({...f,message:e.target.value})}/><div className="rounded-xl bg-[var(--bg)] p-4"><div className="field-label">Typed signature</div><input className="input" placeholder="Type your full name" required value={f.signature_name} onChange={e=>setF({...f,signature_name:e.target.value})}/><p className="mt-2 text-xs leading-5 text-[var(--muted)]">The typed signature must match the full name above.</p></div><Turnstile onToken={setTurnstileToken}/><button className="btn btn-dark" disabled={busy}>{busy?'Submitting…':'Submit request'}</button>{msg&&<p className="text-sm leading-6 text-[var(--muted)]">{msg}</p>}</form></div></Section></main>}
export default function Collaborate(){return <Suspense fallback={<main className="mx-auto max-w-7xl px-5 py-24 text-[var(--muted)]">Loading collaboration form…</main>}><CollaborateForm/></Suspense>}
