'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api} from '../../../lib/api';
import {GitHubRepoSelector} from '../../../components/GitHubRepoSelector';
import {ContentStudio} from '../../../components/ContentStudio';
import {RequestInbox} from '../../../components/RequestInbox';
import {AgreementManager} from '../../../components/AgreementManager';import {VisibilitySettings} from '../../../components/VisibilitySettings';import {MediaUploader} from '../../../components/MediaUploader';import {MediaLibrary} from '../../../components/MediaLibrary';

const tabs=[
 ['overview','Overview'],['analytics','Analytics'],['profile','Profile'],['media','Media'],['projects','Projects'],['research','Research'],['ideas','Ideas'],['experiments','Experiments'],['publications','Publications'],['blog','Notes'],['skills','Skills'],['interests','Interests'],['education','Education'],['experience','Experience'],['social-links','Social links'],['achievements','Achievements'],['timeline','Timeline'],['resume','Resume'],['requests','Requests'],['permissions','Permissions'],['agreements','Agreements'],['visibility','Visibility'],['messages','Messages'],['audit','Audit log']
] as const;

export default function Dashboard(){
 const router=useRouter(); const [me,setMe]=useState<any>(null); const [tab,setTab]=useState<string>('overview'); const [summary,setSummary]=useState<any>(); const [rows,setRows]=useState<any[]>([]); const [msg,setMsg]=useState('');
 useEffect(()=>{api('/auth/me').then(setMe).catch(()=>router.push('/admin/login'))},[router]);
 useEffect(()=>{if(!me)return;setMsg(''); if(tab==='overview'){api<any>('/admin/dashboard-data').then(x=>{setSummary(x.summary);setRows(x.recent_requests||[])}).catch(e=>setMsg(e.message));return} if(['requests','permissions','messages','audit'].includes(tab)){api<any[]>(`/admin/${tab==='audit'?'audit-logs':tab}`).then(setRows).catch(e=>setMsg(e.message));}},[tab,me]);
 async function logout(){await api('/auth/logout',{method:'POST'});router.push('/admin/login')}
 if(!me)return <main className="grid min-h-[70vh] place-items-center text-[var(--muted)]">Checking secure session…</main>;
 const contentTabs=['projects','research','ideas','experiments','publications','blog','skills','interests','education','experience','social-links','resume','achievements','timeline'];
 return <main className="mx-auto max-w-[1500px] px-5 py-8 md:px-8"><header className="flex flex-col justify-between gap-5 border-b border-[var(--line)] pb-7 md:flex-row md:items-end"><div><div className="mono text-[10px] uppercase tracking-[.22em] text-[var(--muted)]">PRIVATE OWNER CMS · SINGLE OWNER</div><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em]">Research Lab Control Room</h1><p className="mt-2 text-sm text-[var(--muted)]">{me.email}</p></div><div className="flex gap-2"><a className="btn" href="/">Open public site</a><button className="btn" onClick={logout}>Sign out</button></div></header><div className="mt-8 grid gap-7 lg:grid-cols-[220px_1fr]"><aside className="lg:sticky lg:top-24 lg:self-start"><div className="card p-3">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`mb-1 w-full rounded-xl px-3 py-2 text-left text-sm ${tab===id?'bg-black text-white':'hover:bg-[var(--bg)]'}`}>{label}</button>)}</div></aside><section className="min-w-0">{tab==='overview'&&<Overview summary={summary} rows={rows} onOpen={setTab}/>} {tab==='media'&&<div className="space-y-6"><MediaUploader/><MediaLibrary/></div>} {tab==='analytics'&&<AnalyticsPanel/>} {tab==='profile'&&<ProfileEditor/>} {contentTabs.includes(tab)&&tab!=='profile'&&<ContentStudio tab={tab as any}/>} {tab==='requests'&&<RequestInbox/>} {tab==='permissions'&&<DataTable title="Permission grants" rows={rows} fields={['id','request_id','rights_json','granted_at','expires_at','revoked_at','notes']}/>} {tab==='messages'&&<Messages rows={rows}/>} {tab==='audit'&&<DataTable title="Audit trail" rows={rows} fields={['created_at','actor_email','action','entity_type','entity_id','metadata_json']}/>} {tab==='agreements'&&<AgreementManager/>}{tab==='visibility'&&<VisibilitySettings/>}{msg&&<div className="mt-5 card p-4 text-sm">{msg}</div>}</section></div></main>
}
function AnalyticsPanel(){const [x,setX]=useState<any>(null);const [err,setErr]=useState('');useEffect(()=>{api('/admin/analytics/report').then(setX).catch(e=>setErr(e.message))},[]);if(err)return <div className="card p-6 text-sm">{err}</div>;if(!x)return <div className="card p-6 text-sm text-[var(--muted)]">Loading analytics…</div>;return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3"><div className="card p-6"><div className="mono text-[10px] text-[var(--muted)]">EVENTS · 30D</div><div className="mt-2 text-3xl font-semibold">{x.total_events}</div></div>{x.by_type.slice(0,2).map((r:any)=><div key={r.event_type} className="card p-6"><div className="mono text-[10px] text-[var(--muted)]">{r.event_type}</div><div className="mt-2 text-3xl font-semibold">{r.count}</div></div>)}</div><div className="grid gap-6 lg:grid-cols-2"><div className="card p-6"><div className="mono text-[10px] text-[var(--muted)]">TOP PATHS</div><div className="mt-4 space-y-3">{x.top_paths.length?x.top_paths.map((r:any)=><div key={r.path} className="flex items-center justify-between gap-4 text-sm"><span className="truncate">{r.path}</span><span className="mono">{r.count}</span></div>):<p className="text-sm text-[var(--muted)]">No analytics recorded yet.</p>}</div></div><div className="card p-6"><div className="mono text-[10px] text-[var(--muted)]">TOP CONTENT</div><div className="mt-4 space-y-3">{x.top_content.length?x.top_content.map((r:any)=><div key={`${r.entity_type}-${r.entity_id}`} className="flex items-center justify-between gap-4 text-sm"><span>{r.entity_type} · {r.entity_id}</span><span className="mono">{r.count}</span></div>):<p className="text-sm text-[var(--muted)]">No content interactions yet.</p>}</div></div></div></div>}
function Overview({summary,rows,onOpen}:{summary:any,rows:any[],onOpen:(t:string)=>void}){const cards=[['Projects',summary?.projects||0,'projects'],['Research',summary?.research||0,'research'],['Ideas',summary?.ideas||0,'ideas'],['Experiments',summary?.experiments||0,'experiments'],['Publications',summary?.publications||0,'publications'],['Pending requests',summary?.pending_requests||0,'requests'],['Unread messages',summary?.unread_messages||0,'messages'],['Real page views · 30d',summary?.page_views_30d||0,'']];return <div className="space-y-7"><MediaUploader/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,target])=><button key={label} className="card p-5 text-left transition hover:-translate-y-0.5" onClick={()=>target&&onOpen(target as string)}><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">{label}</div><div className="mt-3 text-3xl font-semibold">{value}</div></button>)}</div><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="card p-6"><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">WORKFLOW</div><h2 className="mt-2 text-2xl font-semibold">Learn → Think → Research → Experiment → Build → Document → Share → Collaborate</h2><p className="mt-4 max-w-2xl leading-7 text-[var(--muted)]">Keep public content intentional. Draft and review content stays private until you explicitly publish it.</p></div><div className="card p-6"><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">RECENT REQUESTS</div>{!rows.length?<p className="mt-4 text-sm text-[var(--muted)]">No requests yet.</p>:rows.map(r=><div key={r.request_id} className="border-b border-[var(--line)] py-4 last:border-0"><div className="flex justify-between gap-3"><div><div className="font-medium">{r.name}</div><div className="text-xs text-[var(--muted)]">{r.request_id} · {r.status}</div></div><button className="text-xs underline" onClick={()=>onOpen('requests')}>Review</button></div></div>)}</div></div></div>}
function ProfileEditor(){return <ContentStudioProfile/>}
function ContentStudioProfile(){const [value,setValue]=useState<any>(null);const [msg,setMsg]=useState('');useEffect(()=>{api('/admin/profile').then(setValue).catch(e=>setMsg(e.message))},[]);if(!value)return <div className="card p-6">Loading profile…</div>;const fields=['name','tagline','bio','education','board','contact_email','linkedin_url','github_url','github_username','github_featured_repos','orcid_url','contact_email_public','google_scholar_url','arxiv_url','current_learning','research_interests','problem_solving','open_to','avatar_url'];return <div className="card p-7"><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">OWNER PROFILE</div><h2 className="mt-2 text-3xl font-semibold">Public profile</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{fields.map(k=>{const long=['tagline','bio','current_learning','research_interests','problem_solving','open_to','github_featured_repos'].includes(k);if(k==='contact_email_public')return <label key={k} className="card flex items-center gap-3 p-4 text-sm"><input type="checkbox" checked={!!value[k]} onChange={e=>setValue({...value,[k]:e.target.checked})}/><span>Display contact email publicly</span></label>;return <label key={k} className={long?'md:col-span-2':''}><span className="field-label">{k.replaceAll('_',' ')}</span>{long?<textarea className="input min-h-28" value={value[k]||''} onChange={e=>setValue({...value,[k]:e.target.value})}/>:<input className="input" value={value[k]||''} onChange={e=>setValue({...value,[k]:e.target.value})}/>}</label>})}</div><GitHubRepoSelector username={value.github_username||""} selectedValue={value.github_featured_repos||"[]"} onSaved={(x)=>setValue({...value,github_featured_repos:x})}/><div className="mt-6 flex flex-wrap gap-2"><button className="btn btn-dark" onClick={async()=>{try{await api('/admin/profile',{method:'PUT',body:JSON.stringify(value)});setMsg('Profile saved.')}catch(e:any){setMsg(e.message)}}}>Save profile</button><button className="btn" onClick={async()=>{try{const r=await api<any>('/admin/resume/generate',{method:'POST'});setMsg(`Resume generated: ${r.file_url||'saved'}`)}catch(e:any){setMsg(e.message)}}}>Generate PDF resume</button></div>{msg&&<div className="mt-4 text-sm">{msg}</div>}</div>}
function DataTable({title,rows,fields}:{title:string,rows:any[],fields:string[]}){return <div className="card overflow-hidden"><div className="border-b border-[var(--line)] p-6"><div className="mono text-[10px] uppercase tracking-[.18em] text-[var(--muted)]">ADMIN RECORDS</div><h2 className="mt-1 text-2xl font-semibold">{title}</h2></div><div className="overflow-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr>{fields.map(f=><th key={f} className="border-b border-[var(--line)] px-4 py-3 text-left font-medium">{f}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i} className="border-b border-[var(--line)] align-top last:border-0">{fields.map(f=><td key={f} className="max-w-xs px-4 py-3"><div className="break-words text-[var(--muted)]">{typeof r[f]==='object'?JSON.stringify(r[f]):String(r[f]??'')}</div></td>)}</tr>)}</tbody></table></div>{!rows.length&&<div className="p-6 text-sm text-[var(--muted)]">Nothing recorded yet.</div>}</div>}
function Messages({rows}:{rows:any[]}){const [list,setList]=useState(rows);async function mark(id:number){await api(`/admin/messages/${id}/read`,{method:'PATCH'});setList(list.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x))}return <div className="space-y-4">{!list.length&&<div className="card p-6 text-sm text-[var(--muted)]">No messages yet.</div>}{list.map(m=><article key={m.id} className="card p-6"><div className="flex flex-col justify-between gap-3 md:flex-row"><div><h3 className="text-xl font-semibold">{m.name}</h3><div className="text-sm text-[var(--muted)]">{m.email}{m.organization?` · ${m.organization}`:''}</div></div><div className="text-xs text-[var(--muted)]">{new Date(m.created_at).toLocaleString()}</div></div><p className="mt-5 whitespace-pre-wrap leading-7 text-[var(--muted)]">{m.message}</p><button className="btn mt-5" disabled={!!m.read_at} onClick={()=>mark(m.id)}>{m.read_at?'Read':'Mark read'}</button></article>)}</div>}
